services:
  app:
    container_name: kafka-spark-app
    build:
      context: .
    image: kafka-spark-app:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/guest/data